# Generated by Django 4.2.22 on 2025-07-22 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('modified_time', models.TimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('thumbanil', models.ImageField(blank=True, null=True, upload_to='ideas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdeaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='idea_categories')),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IdeaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('modified_time', models.TimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('comment', models.TextField()),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='web.idea')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_comments', to='web.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='idea',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='web.ideacategory'),
        ),
        migrations.AddField(
            model_name='idea',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_ideas', to='web.student'),
        ),
        migrations.CreateModel(
            name='IdeaLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('modified_time', models.TimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='web.idea')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_ideas', to='web.student')),
            ],
            options={
                'unique_together': {('idea', 'student')},
            },
        ),
    ]
