# Generated by Django 4.2.22 on 2025-07-22 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_idea_ideacategory_ideacomment_idea_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_ideas', to='web.student'),
        ),
    ]
