# Generated by Django 4.2.22 on 2025-07-22 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_idea_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='thumbanil',
            new_name='thumbnail',
        ),
    ]
