# Generated by Django 4.2.22 on 2025-07-23 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_thumbanil_idea_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='web.ideacategory'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
