# Generated by Django 4.2.22 on 2025-07-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_idea_category_alter_idea_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
