# Generated by Django 4.2.22 on 2025-07-31 17:44

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_idea_height_idea_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subchapters',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='subchapters/videos'),
        ),
    ]
