# Generated by Django 4.2.22 on 2025-07-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_subchapters_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('modified_time', models.TimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='media')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='subchapters',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='subchapters/videos'),
        ),
    ]
