# Generated by Django 4.2.22 on 2025-08-01 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_media_alter_subchapters_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='file',
        ),
    ]
