# Generated by Django 4.2.22 on 2025-08-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_remove_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='media_type',
            field=models.CharField(default='video', max_length=50),
        ),
        migrations.AddField(
            model_name='media',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
