# Generated by Django 4.2.22 on 2025-08-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_media_duration_media_file_size_media_media_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.AddField(
            model_name='features',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='features'),
        ),
        migrations.AddField(
            model_name='features',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
