# Generated by Django 4.2.22 on 2025-08-01 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_delete_media_features_description_features_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_package', to='web.package'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_package', to='web.package'),
        ),
    ]
