# Generated by Django 4.2.22 on 2025-08-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_batch_package_chapter_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='package',
        ),
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.ManyToManyField(to='web.batch'),
        ),
        migrations.AddField(
            model_name='student',
            name='package',
            field=models.ManyToManyField(blank=True, to='web.package'),
        ),
    ]
