# Generated by Django 4.2.22 on 2025-08-01 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_s3bucketobject'),
        ('web', '0013_remove_student_batch_remove_student_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subchapters',
            name='s3_bucket_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_chapter_s3_bucket_object', to='backend.s3bucketobject'),
        ),
    ]
