# Generated by Django 4.2.22 on 2025-08-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_subchapters_s3_bucket_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subchapters',
            name='s3_bucket_object',
        ),
        migrations.AddField(
            model_name='subchapters',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
