# Generated by Django 4.2.22 on 2025-08-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_remove_subchapters_s3_bucket_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
